Add utils.lookup_device
zwave-js/zwave-js-server pull request #1231
Opened 2024-06-29 15:18 UTC by marcus-j-davies

@AlCalzone , @raman325 

This PR exposes the `lookupDevice` method of the `ConfigManager` class.

I think this should  be added, for the following reason.

Often, after scanning a QR Code, front ends might want to display the Device Information, present in the config.

 - Label
 - Manufatcure
 - Description
 
 etc etc
 
You could argue, why not include this by calling `lookupDevice` during QR Code parsing within the server?
But to allow better 1:1 mapping of the API - I didn't, feel free to suggest otherwise.

Now, I am not too familiar with this code base, so let me know if something is not right with my changes.

2024-08-13 03:57 UTC, raman325 commented
I wonder if this should be in a separate `config` namespace? (so `config.lookup_device` instead of `utils.lookup_device`). I know it's a lot to add a new namespace just for a single command but this might be a good place to put other config related methods

2024-08-14 19:17 UTC, raman325 commented
or maybe `config_manager`

2024-08-15 07:05 UTC, AlCalzone commented
I vote for `utils.`. The config manager isn't going to get any more extensions, so you're looking at 2 methods total (lookup manufacturer by ID and device by fingerprint).

2024-08-15 07:31 UTC, raman325 commented
@marcus-j-davies spoke with Al about this. I added all of the APIs for utils and config manager to be consistent. Sorry for the delayed activity on this but we should be good to merge soon!

2024-08-15 07:49 UTC, AlCalzone requested changes

2024-08-15 07:49 UTC, AlCalzone commented on src/lib/config_manager/command.ts
> +  loadManufacturers = "config_manager.load_manufacturers",
Missing:
- `loadAll`
- `configVersion`

2024-08-15 07:49 UTC, AlCalzone commented on src/lib/utils/command.ts
> +  buffer2hex = "utils.buffer2hex",
IMO formatting numbers/buffers by round-tripping through a websocket seems like unnecessary overhead.

2024-08-15 07:49 UTC, AlCalzone commented on src/lib/utils/command.ts
> +  getEnumMemberName = "utils.get_enum_member_name",
I'm a bit torn on this one, as it's essentially ``enum[value] ?? `unknown (${value})` ``

2024-08-15 07:49 UTC, AlCalzone commented on src/lib/utils/command.ts
> +  rssiToString = "utils.rssi_to_string",
this one is okay, since it's Z-Wave specific.

2024-08-15 07:59 UTC, AlCalzone commented on src/lib/utils/command.ts
> +  buffer2hex = "utils.buffer2hex",
discussed offline, make a note recommending implementing those locally.

2024-08-15 07:59 UTC, AlCalzone commented on src/lib/utils/command.ts
> +  getEnumMemberName = "utils.get_enum_member_name",
discussed offline, make a note recommending implementing those locally.

2024-08-15 08:28 UTC, raman325 commented on src/lib/config_manager/command.ts
> +  loadManufacturers = "config_manager.load_manufacturers",
missing from docs too then :)

2024-08-15 08:50 UTC, AlCalzone commented on src/lib/config_manager/command.ts
> +  loadManufacturers = "config_manager.load_manufacturers",
Whoops

2024-08-15 09:20 UTC, AlCalzone requested changes
Just a small clarification

2024-08-15 09:20 UTC, AlCalzone commented on README.md
> +> NOTE: While some string utility commands are made available in the server due to their availability within the driver, this functionality works best when implemented locally and should not be used
```suggestion
> NOTE: While some string utility commands like `num2hex`, `buffer2hex`, etc. are made available in the server due to their availability within the driver, this functionality works best when implemented locally and should not be used over WebSocket for any practical purpose.
```

2024-08-15 09:20 UTC, AlCalzone approved these changes

2024-08-15 09:23 UTC, merged