Add zniffer support
zwave-js/zwave-js-server pull request #1250
Opened 2024-08-15 09:18 UTC by raman325

Adds zniffer support. Doesn't match the API 1/1 but considering the steps as outlined in the docs seemed to be performed in sequence, it didn't seem to make sense to split them out. Open to alternate suggestions though.

Fixes https://github.com/zwave-js/zwave-js-server/issues/1199

CC @AlCalzone

2024-08-19 08:52 UTC, AlCalzone approved these changes
One thing that still bugs me with this approach is the inability to let a user set up the region before starting the capture. It's probably not very relevant outside of testing setups where devices from multiple regions may be transmitting though.

2024-08-22 03:17 UTC, raman325 commented
is the way to solve that to split init and start? I didn't think there was a practical difference but easy enough to split in two if needed

2024-08-30 06:57 UTC, AlCalzone requested changes
I'd also split `.stop` from `.destroy`, so the capture can be stopped and started again without having to re-initialize.
Other than that, no objections.

2024-08-30 07:07 UTC, AlCalzone approved these changes

2024-08-30 07:10 UTC, merged