Support `get_raw_config_parameter_value`
zwave-js/zwave-js-server pull request #1300
Opened 2024-10-14 05:13 UTC by MindFreeze

We need GET/SET for certification and only set was supported in the server

2024-10-15 06:17 UTC, MindFreeze commented
@AlCalzone Pls review

2024-10-17 06:39 UTC, AlCalzone requested changes

2024-10-17 06:39 UTC, AlCalzone commented on src/lib/node/incoming_message.ts
> +  allowUnexpectedResponse?: boolean;
`allowUnexpectedResponse` is only really needed during the interview, which the driver does internally. I'd probably not expose it to applications.

2024-10-17 06:56 UTC, AlCalzone approved these changes

2024-10-17 07:06 UTC, merged

2024-10-17 10:39 UTC, AlCalzone commented on src/lib/node/command.ts
> +  getRawConfigParameterValue = "node.get_raw_config_parameter_value",
Oh damn, should we have bumped the schema version aswell?

2024-10-17 10:44 UTC, MartinHjelmare commented on src/lib/node/command.ts
> +  getRawConfigParameterValue = "node.get_raw_config_parameter_value",
It was already bumped in another PR in the release, so that's fine. We can just adjust the docs without a new release.