feat: add dockerfile
zwave-js/zwave-js-server pull request #41
Opened 2021-01-17 04:02 UTC by jcam

Not sure this is needed

2021-01-17 11:05 UTC, Michsior14 requested changes

2021-01-17 11:05 UTC, Michsior14 commented on Dockerfile
> +RUN yarn install
```suggestion
RUN npm install
RUN npm run build
```

2021-01-17 11:05 UTC, Michsior14 commented on Dockerfile
> +CMD [ "node_modules/.bin/ts-node", "cli/server.ts", "/dev/ttyUSB0" ]
```suggestion
CMD [ "node", "dist/bin/server.js", "/dev/ttyUSB0" ]
```

2021-01-17 14:02 UTC, Michsior14 approved these changes

2021-01-17 14:02 UTC, Michsior14 commented on .gitignore
> +yarn.lock
We don't need yarn.lock here anymore :)

2021-01-17 14:02 UTC, Michsior14 commented on .dockerignore
> +yarn.lock
You could add `package-lock.json` as well.

2021-01-17 14:49 UTC, jcam commented
Ah, I was modifying an old version and somehow had my git origins set up wrong so I didn't realize it. Rebasing...

2021-01-17 16:31 UTC, balloob commented on Dockerfile
> +CMD [ "node", "dist/bin/server.js", "/dev/ttyUSB0" ]
This makes no sense to hardcode to this path. People need to get their serial stick into Docker.

2021-01-17 16:33 UTC, balloob commented
What would be the use of adding this Dockerfile ?

2021-01-17 17:01 UTC, jcam commented
It is the dockerfile that I use to generate a package for deploying to my nuc. If not useful, close it out. I was just offering it in case others would find it useful, rather than figuring out how to build it themselves. Could also put it in a docs/examples folder or something

2021-01-17 17:03 UTC, Michsior14 commented
> It is the dockerfile that I use to generate a package for deploying to my nuc. If not useful, close it out. I was just offering it in case others would find it useful, rather than figuring out how to build it themselves. Could also put it in a docs/examples folder or something

I could also see that happening on my end. I tent to keep zwave controller separately of HassOS.

2021-01-18 12:58 UTC, balloob commented on Dockerfile
> +CMD [ "node", "dist/bin/server.js", "/dev/ttyUSB0" ]
And also please add a section to the README how to use this Docker file.

2021-01-19 06:11 UTC, jcam commented
Closing for now in favor of https://github.com/kpine/dockerfiles/tree/main/zwave-js-server

2021-01-19 06:11 UTC, closed without merging